# Generated by Django 5.2.10 on 2026-01-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPerformanceInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_videos', models.IntegerField(default=0)),
                ('avg_views', models.FloatField(default=0.0)),
                ('avg_engagement_rate', models.FloatField(default=0.0)),
                ('best_video_views', models.BigIntegerField(default=0)),
                ('trend_direction', models.CharField(choices=[('up', 'Trending Up'), ('down', 'Trending Down'), ('stable', 'Stable')], default='stable', max_length=20)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-avg_views'],
            },
        ),
        migrations.CreateModel(
            name='DailyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('videos_uploaded', models.IntegerField(default=0)),
                ('total_views', models.BigIntegerField(default=0)),
                ('total_likes', models.BigIntegerField(default=0)),
                ('total_comments', models.BigIntegerField(default=0)),
                ('total_shares', models.BigIntegerField(default=0)),
                ('followers_start', models.IntegerField(default=0)),
                ('followers_end', models.IntegerField(default=0)),
                ('followers_gained', models.IntegerField(default=0)),
                ('avg_engagement_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Daily Analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HookPerformanceInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hook_type', models.CharField(db_index=True, max_length=20)),
                ('total_uses', models.IntegerField(default=0)),
                ('avg_views', models.FloatField(default=0.0)),
                ('avg_engagement_rate', models.FloatField(default=0.0)),
                ('avg_completion_rate', models.FloatField(default=0.0)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-avg_engagement_rate'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, max_length=20)),
                ('category', models.CharField(choices=[('content_generation', 'Content Generation'), ('video_creation', 'Video Creation'), ('upload', 'Upload'), ('automation', 'Automation'), ('analytics', 'Analytics'), ('system', 'System')], db_index=True, max_length=30)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.BigIntegerField(default=0)),
                ('likes', models.BigIntegerField(default=0)),
                ('comments', models.BigIntegerField(default=0)),
                ('shares', models.BigIntegerField(default=0)),
                ('saves', models.BigIntegerField(default=0)),
                ('engagement_rate', models.FloatField(default=0.0, help_text='(likes + comments + shares) / views')),
                ('watch_time_avg', models.FloatField(default=0.0, help_text='Average watch time in seconds')),
                ('completion_rate', models.FloatField(default=0.0, help_text='Percentage who watched to end')),
                ('followers_gained', models.IntegerField(default=0)),
                ('profile_views', models.IntegerField(default=0)),
                ('first_hour_views', models.IntegerField(default=0)),
                ('first_day_views', models.IntegerField(default=0)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-views'],
            },
        ),
    ]
