# Generated by Django 5.2.10 on 2026-01-22 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('analytics', '0001_initial'),
        ('content', '0001_initial'),
        ('media_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentperformanceinsight',
            name='best_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_engine.video'),
        ),
        migrations.AddField(
            model_name='contentperformanceinsight',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='content.contentcategory'),
        ),
        migrations.AddField(
            model_name='dailyanalytics',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='accounts.tiktokaccount'),
        ),
        migrations.AddField(
            model_name='hookperformanceinsight',
            name='best_hook_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.hooktemplate'),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='accounts.tiktokaccount'),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='media_engine.video'),
        ),
        migrations.AddField(
            model_name='videoperformance',
            name='upload_schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='accounts.uploadschedule'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyanalytics',
            unique_together={('account', 'date')},
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['level', '-created_at'], name='analytics_s_level_8ec416_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['category', '-created_at'], name='analytics_s_categor_a588a4_idx'),
        ),
    ]
