# Generated by Django 5.2.10 on 2026-01-22 17:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_human_behavior', models.BooleanField(default=True)),
                ('random_delay_min_seconds', models.IntegerField(default=30)),
                ('random_delay_max_seconds', models.IntegerField(default=180)),
                ('enable_mouse_movement', models.BooleanField(default=True)),
                ('mouse_speed_min', models.FloatField(default=0.5)),
                ('mouse_speed_max', models.FloatField(default=1.5)),
                ('page_load_wait_min', models.IntegerField(default=2)),
                ('page_load_wait_max', models.IntegerField(default=5)),
                ('max_daily_uploads_global', models.IntegerField(default=10)),
                ('enable_overnight_pause', models.BooleanField(default=True)),
                ('overnight_start_hour', models.IntegerField(default=23)),
                ('overnight_end_hour', models.IntegerField(default=7)),
                ('enable_random_breaks', models.BooleanField(default=True)),
                ('break_probability', models.FloatField(default=0.15, help_text='15% chance of taking a break day')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Automation Settings',
            },
        ),
        migrations.CreateModel(
            name='TikTokAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('banned', 'Banned'), ('warming', 'Warming Up')], default='warming', max_length=20)),
                ('is_automation_enabled', models.BooleanField(default=False)),
                ('account_created_date', models.DateField(help_text='When the TikTok account was created')),
                ('automation_start_date', models.DateField(blank=True, null=True)),
                ('max_videos_per_day', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('min_hours_between_posts', models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(24)])),
                ('session_data', models.JSONField(blank=True, default=dict, help_text='Encrypted session cookies')),
                ('session_last_updated', models.DateTimeField(blank=True, null=True)),
                ('session_is_valid', models.BooleanField(default=False)),
                ('last_upload_time', models.DateTimeField(blank=True, null=True)),
                ('consecutive_upload_days', models.IntegerField(default=0)),
                ('total_uploads', models.IntegerField(default=0)),
                ('risk_score', models.IntegerField(default=0, help_text='Higher score = higher risk', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('last_risk_check', models.DateTimeField(auto_now=True)),
                ('total_views', models.BigIntegerField(default=0)),
                ('total_likes', models.BigIntegerField(default=0)),
                ('total_shares', models.BigIntegerField(default=0)),
                ('follower_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_type', models.CharField(blank=True, max_length=100)),
                ('error_details', models.TextField(blank=True)),
                ('browser_logs', models.JSONField(blank=True, default=dict)),
                ('screenshots', models.JSONField(blank=True, default=list, help_text='Paths to debug screenshots')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField(db_index=True)),
                ('actual_upload_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('uploading', 'Uploading'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('upload_started', models.DateTimeField(blank=True, null=True)),
                ('upload_completed', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('tiktok_video_id', models.CharField(blank=True, max_length=100)),
                ('tiktok_url', models.URLField(blank=True)),
                ('pre_upload_delay', models.IntegerField(default=0, help_text='Random delay in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_uploads', to='accounts.tiktokaccount')),
            ],
            options={
                'ordering': ['scheduled_time'],
            },
        ),
    ]
