# Generated by Django 5.2.10 on 2026-01-22 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('content', '0001_initial'),
        ('media_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadschedule',
            name='caption',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_schedules', to='content.caption'),
        ),
        migrations.AddField(
            model_name='uploadschedule',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_schedules', to='media_engine.video'),
        ),
        migrations.AddField(
            model_name='uploadlog',
            name='upload_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='accounts.uploadschedule'),
        ),
        migrations.AddIndex(
            model_name='uploadschedule',
            index=models.Index(fields=['status', 'scheduled_time'], name='accounts_up_status_1e5640_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadschedule',
            index=models.Index(fields=['account', 'status'], name='accounts_up_account_e78f60_idx'),
        ),
    ]
