# Generated by Django 5.2.10 on 2026-01-22 17:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='TikTok caption (max 2200 chars)', max_length=2200)),
                ('hashtags', models.CharField(help_text='Comma-separated hashtags', max_length=500)),
                ('style', models.CharField(default='engaging', max_length=50)),
                ('emoji_count', models.IntegerField(default=3)),
                ('is_used', models.BooleanField(default=False)),
                ('performance_score', models.IntegerField(default=0, help_text='Based on video performance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=200, unique=True)),
                ('blacklist_type', models.CharField(choices=[('medical', 'Medical Claims'), ('political', 'Political'), ('sensitive', 'Sensitive Topics'), ('profanity', 'Profanity'), ('other', 'Other')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['blacklist_type', 'phrase'],
            },
        ),
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Content Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HookTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hook_type', models.CharField(choices=[('curiosity', 'Curiosity'), ('shock', 'Shock'), ('question', 'Question'), ('attention', 'Attention')], max_length=20)),
                ('template', models.CharField(help_text='Use {fact} as placeholder', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['usage_count', '-last_used'],
            },
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The actual fact (1-2 sentences)')),
                ('full_script', models.TextField(help_text='Hook + Fact combined')),
                ('ai_provider', models.CharField(default='openai', max_length=50)),
                ('generation_prompt', models.TextField(blank=True)),
                ('content_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('similarity_checked', models.BooleanField(default=False)),
                ('is_used', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('quality_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='content.contentcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
