# Generated by Django 5.2.10 on 2026-01-22 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('media_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='used_in_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fact_used', to='media_engine.video'),
        ),
        migrations.AddField(
            model_name='caption',
            name='fact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captions', to='content.fact'),
        ),
        migrations.AddField(
            model_name='fact',
            name='hook_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.hooktemplate'),
        ),
        migrations.AddIndex(
            model_name='fact',
            index=models.Index(fields=['is_used', 'is_approved'], name='content_fac_is_used_f9fb9c_idx'),
        ),
        migrations.AddIndex(
            model_name='fact',
            index=models.Index(fields=['category', 'is_approved'], name='content_fac_categor_d94e79_idx'),
        ),
    ]
