# Generated by Django 5.2.10 on 2026-01-22 17:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('video_type', models.CharField(choices=[('nature', 'Nature'), ('city', 'City Timelapse'), ('abstract', 'Abstract Visuals'), ('space', 'Space'), ('ocean', 'Ocean')], max_length=20)),
                ('file', models.FileField(upload_to='backgrounds/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi'])])),
                ('duration', models.FloatField(help_text='Duration in seconds')),
                ('resolution', models.CharField(default='1080x1920', max_length=20)),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['usage_count', '-last_used'],
            },
        ),
        migrations.CreateModel(
            name='VoiceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider', models.CharField(choices=[('elevenlabs', 'ElevenLabs'), ('gtts', 'Google TTS')], max_length=20)),
                ('voice_id', models.CharField(help_text='Provider-specific voice ID', max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('speed_multiplier', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(2.0)])),
                ('pitch', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)])),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['usage_count', '-last_used'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('subtitle_file', models.FileField(blank=True, null=True, upload_to='subtitles/')),
                ('final_video', models.FileField(blank=True, null=True, upload_to='videos/generated/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('duration', models.FloatField(default=0, help_text='Duration in seconds')),
                ('resolution', models.CharField(default='1080x1920', max_length=20)),
                ('file_size', models.BigIntegerField(default=0, help_text='Size in bytes')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('generation_started', models.DateTimeField(blank=True, null=True)),
                ('generation_completed', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('subtitle_font_size', models.IntegerField(default=48)),
                ('subtitle_position', models.CharField(default='center', max_length=20)),
                ('subtitle_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('background_video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_engine.backgroundvideo')),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='content.fact')),
                ('voice_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_engine.voiceprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubtitleSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('start_time', models.FloatField(help_text='Start time in seconds')),
                ('end_time', models.FloatField(help_text='End time in seconds')),
                ('sequence', models.IntegerField(help_text='Order of appearance')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitle_segments', to='media_engine.video')),
            ],
            options={
                'ordering': ['video', 'sequence'],
                'unique_together': {('video', 'sequence')},
            },
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['status', '-created_at'], name='media_engin_status_5b9c90_idx'),
        ),
    ]
